package com.aiusage.monitor.bridge;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.Locale;

/**
 * The digest a paired phone remembers its computer by: SHA-256 over the certificate's
 * SubjectPublicKeyInfo, as hex. Spec §21, docs/PHASE-7-PLAN.md A8.
 *
 * <p>Why the public key and not the whole certificate: the certificate is
 * re-issued whenever its validity or subject changes, while the key is what pairing
 * is about — the phone trusts "whoever holds this private key". Pinning the
 * certificate would turn a routine renewal into "every phone must pair again", and
 * pinning the subject would pin a name the Bridge does not have (its CN is a random
 * id, and it has no LAN address in the SANs).
 *
 * <p>The same digest is what the Bridge advertises in its pairing offer and in
 * {@code /v1/health}, and what the Go side computes in
 * {@code bridge/internal/identity}. The two are pinned to each other by the test
 * vectors in {@code FingerprintPinTest}, which are generated by the real Go code.
 */
public final class FingerprintPin {

    private final String fingerprint;
    public static final String CERTIFICATE_PREFIX = "cert-sha256:";
    private final boolean certificatePin;

    /**
     * @param fingerprint hex SHA-256 of a certificate's SPKI, as the offer carried it
     * @throws IllegalArgumentException when it is not such a digest — a truncated
     *         paste must not become "pin the empty string", which would accept every
     *         certificate on the network
     */
    public FingerprintPin(String fingerprint) {
        certificatePin = fingerprint != null && fingerprint.startsWith(CERTIFICATE_PREFIX);
        String digest = certificatePin ? fingerprint.substring(CERTIFICATE_PREFIX.length()) : fingerprint;
        if (digest == null || !digest.matches("^[0-9a-fA-F]{64}$")) {
            throw new IllegalArgumentException("指纹不是一枚 SHA-256 摘要");
        }
        this.fingerprint = (certificatePin ? CERTIFICATE_PREFIX : "") + digest.toLowerCase(Locale.US);
    }

    public String value() {
        return fingerprint;
    }

    /** The tail a person compares against the computer's terminal (A11). */
    public String tail() {
        return ManualTarget.tailOf(certificatePin
                ? fingerprint.substring(CERTIFICATE_PREFIX.length()) : fingerprint);
    }

    public boolean matches(Certificate certificate) {
        byte[] digest;
        try {
            digest = certificatePin && certificate != null
                    ? MessageDigest.getInstance("SHA-256").digest(certificate.getEncoded())
                    : digestOf(certificate);
        } catch (java.security.GeneralSecurityException exception) {
            return false;
        }
        return digest != null
                && MessageDigest.isEqual(digest, hexToBytes(certificatePin
                        ? fingerprint.substring(CERTIFICATE_PREFIX.length()) : fingerprint));
    }

    /** Null when the certificate carries no encodable public key. */
    public static byte[] digestOf(Certificate certificate) {
        if (certificate == null) {
            return null;
        }
        try {
            // X509.getPublicKey().getEncoded() is the DER SubjectPublicKeyInfo, the
            // same structure Go marshals with x509.MarshalPKIXPublicKey.
            return MessageDigest.getInstance("SHA-256")
                    .digest(certificate.getPublicKey().getEncoded());
        } catch (NoSuchAlgorithmException | IllegalArgumentException exception) {
            return null;
        }
    }

    public static String hexOf(Certificate certificate) {
        byte[] digest = digestOf(certificate);
        return digest == null ? "" : bytesToHex(digest);
    }

    private static String bytesToHex(byte[] bytes) {
        StringBuilder text = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            text.append(Character.forDigit((b >> 4) & 0xF, 16));
            text.append(Character.forDigit(b & 0xF, 16));
        }
        return text.toString();
    }

    private static byte[] hexToBytes(String hex) {
        byte[] out = new byte[hex.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return out;
    }
}
